import { CrewMember } from '@/types/crew';

export const MOCK_CREW_LIST: CrewMember[] = [
    {
        id: "crew_1",
        name: "이나현",
        profileImage: "/images/CrewImg.png",
        position: 1,
        department: "소프트웨어",
        studentNumber: "22",
        generation: 0,
        active: 'ACTIVE',
        emailAddress: "nahyun@ajou.ac.kr",
        description: "새로운 기술을 배우는 것을 좋아하는 신입 크루입니다.",
        follower: 15,
        following: 20,
        activityCount: 10,
        blogCount: 5,
    },
    {
        id: "crew_2",
        name: "조예진",
        profileImage: "/images/CrewImg.png",
        position: 2,
        department: "소프트웨어",
        studentNumber: "21",
        generation: 0,
        active: 'ACTIVE',
        emailAddress: "yejin@ajou.ac.kr",
        description: "아올다의 1기 회장을 맡고 있는 이영희입니다.",
        follower: 250,
        following: 180,
        activityCount: 24,
        blogCount: 12,
    },
    {
        id: "crew_3",
        name: "김화균",
        profileImage: "/images/CrewImg.png",
        position: 3,
        department: "사이버보안",
        studentNumber: "21",
        generation: 0,
        active: 'ACTIVE',
        emailAddress: "hwagyun@ajou.ac.kr",
        description: "꼼꼼한 설계와 기록을 중요하게 생각합니다.",
        follower: 85,
        following: 90,
        activityCount: 10,
        blogCount: 5,
    },
    {
        id: "crew_4",
        name: "천진강",
        profileImage: "/images/CrewImg.png",
        position: 4,
        department: "사이버보안",
        studentNumber: "21",
        generation: 1,
        active: 'ACTIVE',
        emailAddress: "jingang@ajou.ac.kr",
        description: "꼼꼼한 설계와 기록을 중요하게 생각합니다.",
        follower: 85,
        following: 90,
        activityCount: 10,
        blogCount: 5,
    },
    {
        id: "crew_5",
        name: "한동현",
        profileImage: "/images/CrewImg.png",
        position: 4,
        department: "사이버보안",
        studentNumber: "21",
        generation: 1,
        active: 'ACTIVE',
        emailAddress: "donghyeon@ajou.ac.kr",
        description: "꼼꼼한 설계와 기록을 중요하게 생각합니다.",
        follower: 85,
        following: 90,
        activityCount: 10,
        blogCount: 5,
    },
    {
        id: "crew_6",
        name: "문서현",
        profileImage: "/images/CrewImg.png",
        position: 4,
        department: "소프트웨어",
        studentNumber: "21",
        generation: 1,
        active: 'ACTIVE',
        emailAddress: "seohyeon@ajou.ac.kr",
        description: "꼼꼼한 설계와 기록을 중요하게 생각합니다.",
        follower: 85,
        following: 90,
        activityCount: 10,
        blogCount: 5,
    },
    {
        id: "crew_7",
        name: "박병언",
        profileImage: "/images/CrewImg.png",
        position: 4,
        department: "소프트웨어",
        studentNumber: "21",
        generation: 1,
        active: 'ACTIVE',
        emailAddress: "byeongeon@ajou.ac.kr",
        description: "꼼꼼한 설계와 기록을 중요하게 생각합니다.",
        follower: 85,
        following: 90,
        activityCount: 10,
        blogCount: 5,
    },
    {
        id: "crew_8",
        name: "김철수",
        profileImage: "/images/CrewImg.png",
        position: 4,
        department: "디지털미디어",
        studentNumber: "21",
        generation: 2,
        active: 'ACTIVE',
        emailAddress: "cheolsoo@ajou.ac.kr",
        description: "꼼꼼한 설계와 기록을 중요하게 생각합니다.",
        follower: 85,
        following: 90,
        activityCount: 10,
        blogCount: 5,
    },
    {
        id: "crew_9",
        name: "이영희",
        profileImage: "/images/CrewImg.png",
        position: 4,
        department: "디지털미디어",
        studentNumber: "21",
        generation: 2,
        active: 'ACTIVE',
        emailAddress: "yeonghee@ajou.ac.kr",
        description: "꼼꼼한 설계와 기록을 중요하게 생각합니다.",
        follower: 85,
        following: 90,
        activityCount: 10,
        blogCount: 5,
    },
];